---
name: Algorithm-CurveFit
version: 1.03
author:
  - 'Steffen Mueller <smueller@cpan.org>'
abstract: Nonlinear Least Squares Fitting
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Data::Dumper: 0
  Math::MatrixReal: 0
  Math::Symbolic: 0.128
build_requires:
  Test::More: 0
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
provides:
  Algorithm::CurveFit:
    file: lib/Algorithm/CurveFit.pm
    version: 1.03
generated_by: Module::Build version 0.280501
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
