# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Algorithm-CurveFit
version:      1.01
version_from: lib/Algorithm/CurveFit.pm
installdirs:  site
requires:
    Data::Dumper:                  0
    Math::MatrixReal:              0
    Math::Symbolic:                0.128
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
