--- #YAML:1.0
name: Algorithm-CurveFit
version: 1.02
author:
  - |-
    Steffen Mueller <curvefit-module at steffen-mueller dot net>
abstract: Nonlinear Least Squares Fitting
license: perl
requires:
  Data::Dumper: 0
  Math::MatrixReal: 0
  Math::Symbolic: 0.128
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
build_requires:
  Test::More: 0
provides:
  Algorithm::CurveFit:
    file: lib/Algorithm/CurveFit.pm
    version: 1.02
generated_by: Module::Build version 0.2608
