---
abstract: 'Nonlinear Least Squares Fitting'
author:
  - 'Steffen Mueller <smueller@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3605'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Algorithm-CurveFit
provides:
  Algorithm::CurveFit:
    file: lib/Algorithm/CurveFit.pm
    version: 1.05
recommends:
  Test::Pod: 1.0
  Test::Pod::Coverage: 1.0
requires:
  Data::Dumper: 0
  Math::MatrixReal: 0
  Math::Symbolic: 0.602
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 1.05
